const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  loadConfig: (file) => ipcRenderer.invoke('load-config', file),
  openFile: (kind) => ipcRenderer.invoke('open-file', kind),
  saveFile: (content, kind = 'json', defaultPath, options = {}) => ipcRenderer.invoke('save-file', { content, kind, defaultPath, ...options }),
  quickSaveFile: (data) => ipcRenderer.invoke('quick-save-file', data),
  openNewWindow: () => ipcRenderer.invoke('openNewWindow'),
  loadFileInNewWindow: (kind) => ipcRenderer.invoke('load-file-in-new-window', kind),
  chooseAivSkin: (itemType) => ipcRenderer.invoke('choose-aiv-skin', itemType),
  removeAivSkin: (itemType) => ipcRenderer.invoke('remove-aiv-skin', itemType),
  loadAivSkins: () => ipcRenderer.invoke('load-aiv-skins'),
  openAivSkinsFolder: () => ipcRenderer.invoke('open-aiv-skins-folder'),
  confirmUnsaved: (details) => ipcRenderer.invoke('confirm-unsaved', details),
  confirmWindowClose: () => ipcRenderer.send('confirm-window-close'),
  getUcpInstallation: () => ipcRenderer.invoke('get-ucp-installation'),
  chooseUcpInstallation: () => ipcRenderer.invoke('choose-ucp-installation'),
  chooseCastleBackground: () => ipcRenderer.invoke('choose-castle-background'),
  listGameMaps: () => ipcRenderer.invoke('list-game-maps'),
  loadGameMap: (filePath) => ipcRenderer.invoke('load-game-map', filePath),
  loadMapTerrain: (request) => ipcRenderer.invoke('load-map-terrain', request),
  scanUcpAiLibrary: (gameRoot) => ipcRenderer.invoke('scan-ucp-ai-library', gameRoot),
  loadUcpAiProject: (request) => ipcRenderer.invoke('load-ucp-ai-project', request),
  updateAiCastleMapping: (request) => ipcRenderer.invoke('update-ai-castle-mapping', request),
  cloneUcpAi: (request) => ipcRenderer.invoke('clone-ucp-ai', request),
  createUcpAi: (request) => ipcRenderer.invoke('create-ucp-ai', request),
  updateUcpAi: (request) => ipcRenderer.invoke('update-ucp-ai', request),
  chooseAiPortrait: (request) => ipcRenderer.invoke('choose-ai-portrait', request),
  loadAiMediaData: (request) => ipcRenderer.invoke('load-ai-media-data', request),
  replaceAiMedia: (request) => ipcRenderer.invoke('replace-ai-media', request),
  openAiMedia: (request) => ipcRenderer.invoke('open-ai-media', request),
  openUcpPath: (request) => ipcRenderer.invoke('open-ucp-path', request),
  setActiveWorkspace: (workspace) => ipcRenderer.send('set-active-workspace', workspace),
  setCastleOverviewPreferences: (preferences) => ipcRenderer.send('set-castle-overview-preferences', preferences),

  onLoadFile: (callback) => {
    ipcRenderer.removeAllListeners('load-file');
    ipcRenderer.on('load-file', (_event, data) => callback(data));
  },
  onTriggerLoad: (callback) => ipcRenderer.on('trigger-load', callback),
  onTriggerNewDocument: (callback) => ipcRenderer.on('trigger-new-document', callback),
  onTriggerSave: (callback) => ipcRenderer.on('trigger-save', callback),
  onTriggerSaveAs: (callback) => ipcRenderer.on('trigger-save-as', callback),
  onTriggerNewWindow: (callback) => ipcRenderer.on('trigger-new-window', callback),
  onTriggerLoadInWindow: (callback) => ipcRenderer.on('trigger-load-in-window', callback),
  onTriggerToggleOx: (callback) => ipcRenderer.on('trigger-toggle-ox', callback),
  onTriggerToggleRunning: (callback) => ipcRenderer.on('trigger-toggle-running', callback),
  onTriggerStandardOrder: (callback) => ipcRenderer.on('trigger-set-standard-order', callback),
  onTriggerOrderedOrder: (callback) => ipcRenderer.on('trigger-set-ordered-order', callback),
  onTriggerToggleSections: (callback) => ipcRenderer.on('trigger-toggle-section', callback),
  onTriggerWorkspace: (callback) => ipcRenderer.on('trigger-workspace', (_event, workspace) => callback(workspace)),
  onTriggerUndo: (callback) => ipcRenderer.on('trigger-undo', callback),
  onTriggerRedo: (callback) => ipcRenderer.on('trigger-redo', callback),
  onTriggerDeleteSelected: (callback) => ipcRenderer.on('trigger-delete-selected', callback),
  onTriggerLoadCastleBackground: (callback) => ipcRenderer.on('trigger-load-castle-background', callback),
  onTriggerClearCastleBackground: (callback) => ipcRenderer.on('trigger-clear-castle-background', callback),
  onTriggerEditCastleMapping: (callback) => ipcRenderer.on('trigger-edit-castle-mapping', callback),
  onTriggerCustomizeCastleShortcuts: (callback) => ipcRenderer.on('trigger-customize-castle-shortcuts', callback),
  onTriggerCastleOverview: (callback) => ipcRenderer.on('trigger-castle-overview', (_event, command) => callback(command)),
  onRequestWindowClose: (callback) => ipcRenderer.on('request-window-close', callback)
});
