; Generated by node scripts/package-policy.mjs --write. Do not hand edit.
; Editable configuration is user data: add missing defaults, never replace or delete.
!ifndef TOOLKIT_DEFAULT_CONFIG_DIR
  !define TOOLKIT_DEFAULT_CONFIG_DIR "${__FILEDIR__}\..\..\config"
!endif

!macro NSIS_HOOK_POSTINSTALL
  SetOutPath "$INSTDIR\config"
  SetOverwrite off
  File "${TOOLKIT_DEFAULT_CONFIG_DIR}\*.json"
  SetOverwrite lastused
  SetOutPath "$INSTDIR"
!macroend
