; Tauri 2.11.5 NSIS custom strings. Preserve NSIS/Handlebars substitutions.
LangString addOrReinstall ${LANG_FARSI} "افزودن یا نصب مجدد اجزا"
LangString alreadyInstalled ${LANG_FARSI} "از قبل نصب شده است"
LangString alreadyInstalledLong ${LANG_FARSI} "${PRODUCTNAME} ${VERSION} از قبل نصب شده است. عملیات مورد نظر را انتخاب کنید و برای ادامه روی «بعدی» کلیک کنید."
LangString appRunning ${LANG_FARSI} "{{product_name}} در حال اجراست! ابتدا آن را ببندید و دوباره تلاش کنید."
LangString appRunningOkKill ${LANG_FARSI} "{{product_name}} در حال اجراست!$\nبرای توقف اجباری آن روی «تأیید» کلیک کنید."
LangString chooseMaintenanceOption ${LANG_FARSI} "عملیات نگهداری مورد نظر را انتخاب کنید."
LangString choowHowToInstall ${LANG_FARSI} "روش نصب ${PRODUCTNAME} را انتخاب کنید."
LangString createDesktop ${LANG_FARSI} "ایجاد میان‌بر روی دسکتاپ"
LangString dontUninstall ${LANG_FARSI} "حذف نشود"
LangString dontUninstallDowngrade ${LANG_FARSI} "حذف نشود (نصب نسخهٔ قدیمی‌تر بدون حذف نسخهٔ فعلی مجاز نیست)"
LangString failedToKillApp ${LANG_FARSI} "توقف {{product_name}} ناموفق بود. ابتدا آن را ببندید و دوباره تلاش کنید."
LangString installingWebview2 ${LANG_FARSI} "در حال نصب WebView2..."
LangString newerVersionInstalled ${LANG_FARSI} "نسخهٔ جدیدتری از ${PRODUCTNAME} از قبل نصب شده است! نصب نسخهٔ قدیمی‌تر توصیه نمی‌شود. اگر می‌خواهید این نسخهٔ قدیمی‌تر را نصب کنید، بهتر است ابتدا نسخهٔ فعلی را حذف کنید. عملیات مورد نظر را انتخاب کنید و برای ادامه روی «بعدی» کلیک کنید."
LangString older ${LANG_FARSI} "قدیمی‌تر"
LangString olderOrUnknownVersionInstalled ${LANG_FARSI} "نسخه‌ای $R4 از ${PRODUCTNAME} روی سیستم نصب شده است. توصیه می‌شود پیش از نصب، نسخهٔ فعلی را حذف کنید. عملیات مورد نظر را انتخاب کنید و برای ادامه روی «بعدی» کلیک کنید."
LangString silentDowngrades ${LANG_FARSI} "این نصب‌کننده اجازهٔ نصب نسخهٔ قدیمی‌تر را نمی‌دهد و نصب بدون رابط کاربری نمی‌تواند ادامه یابد. لطفاً از نصب‌کنندهٔ گرافیکی استفاده کنید.$\n"
LangString unableToUninstall ${LANG_FARSI} "حذف برنامه امکان‌پذیر نیست!"
LangString uninstallApp ${LANG_FARSI} "حذف ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_FARSI} "حذف نسخهٔ فعلی پیش از نصب"
LangString unknown ${LANG_FARSI} "ناشناخته"
LangString webview2AbortError ${LANG_FARSI} "نصب WebView2 ناموفق بود! برنامه بدون آن اجرا نمی‌شود. نصب‌کننده را دوباره اجرا کنید."
LangString webview2DownloadError ${LANG_FARSI} "خطا: دریافت WebView2 ناموفق بود — $0"
LangString webview2DownloadSuccess ${LANG_FARSI} "برنامهٔ راه‌انداز نصب WebView2 با موفقیت دریافت شد"
LangString webview2Downloading ${LANG_FARSI} "در حال دریافت برنامهٔ راه‌انداز نصب WebView2..."
LangString webview2InstallError ${LANG_FARSI} "خطا: نصب WebView2 با کد خروج $1 ناموفق بود"
LangString webview2InstallSuccess ${LANG_FARSI} "WebView2 با موفقیت نصب شد"
LangString deleteAppData ${LANG_FARSI} "حذف داده‌های برنامه"
