; Tauri 2.11.5 NSIS custom strings. Preserve NSIS/Handlebars substitutions.
LangString addOrReinstall ${LANG_HUNGARIAN} "Összetevők hozzáadása vagy újratelepítése"
LangString alreadyInstalled ${LANG_HUNGARIAN} "Már telepítve"
LangString alreadyInstalledLong ${LANG_HUNGARIAN} "A(z) ${PRODUCTNAME} ${VERSION} már telepítve van. Válassza ki a kívánt műveletet, majd kattintson a Tovább gombra."
LangString appRunning ${LANG_HUNGARIAN} "A(z) {{product_name}} fut! Zárja be, majd próbálja újra."
LangString appRunningOkKill ${LANG_HUNGARIAN} "A(z) {{product_name}} fut!$\nAz OK gombbal leállíthatja."
LangString chooseMaintenanceOption ${LANG_HUNGARIAN} "Válassza ki a végrehajtandó karbantartási műveletet."
LangString choowHowToInstall ${LANG_HUNGARIAN} "Válassza ki a(z) ${PRODUCTNAME} telepítésének módját."
LangString createDesktop ${LANG_HUNGARIAN} "Asztali parancsikon létrehozása"
LangString dontUninstall ${LANG_HUNGARIAN} "Ne távolítsa el"
LangString dontUninstallDowngrade ${LANG_HUNGARIAN} "Ne távolítsa el (eltávolítás nélkül nem telepíthető régebbi verzió)"
LangString failedToKillApp ${LANG_HUNGARIAN} "Nem sikerült leállítani a(z) {{product_name}} alkalmazást. Zárja be, majd próbálja újra."
LangString installingWebview2 ${LANG_HUNGARIAN} "A WebView2 telepítése..."
LangString newerVersionInstalled ${LANG_HUNGARIAN} "A(z) ${PRODUCTNAME} újabb verziója már telepítve van. Régebbi verzió telepítése nem ajánlott. Ha mégis ezt szeretné, előbb távolítsa el a jelenlegi verziót. Válassza ki a kívánt műveletet, majd kattintson a Tovább gombra."
LangString older ${LANG_HUNGARIAN} "régebbi"
LangString olderOrUnknownVersionInstalled ${LANG_HUNGARIAN} "A(z) ${PRODUCTNAME} egy $R4 verziója van telepítve. Telepítés előtt ajánlott eltávolítani a jelenlegi verziót. Válassza ki a kívánt műveletet, majd kattintson a Tovább gombra."
LangString silentDowngrades ${LANG_HUNGARIAN} "Ez a telepítő nem engedélyezi régebbi verzió telepítését. A csendes telepítés nem folytatható; használja a grafikus telepítőt.$\n"
LangString unableToUninstall ${LANG_HUNGARIAN} "Az eltávolítás nem sikerült!"
LangString uninstallApp ${LANG_HUNGARIAN} "A(z) ${PRODUCTNAME} eltávolítása"
LangString uninstallBeforeInstalling ${LANG_HUNGARIAN} "Eltávolítás a telepítés előtt"
LangString unknown ${LANG_HUNGARIAN} "ismeretlen"
LangString webview2AbortError ${LANG_HUNGARIAN} "A WebView2 telepítése nem sikerült! Az alkalmazás nélküle nem futtatható. Indítsa újra a telepítőt."
LangString webview2DownloadError ${LANG_HUNGARIAN} "Hiba: a WebView2 letöltése nem sikerült – $0"
LangString webview2DownloadSuccess ${LANG_HUNGARIAN} "A WebView2 indítótelepítője sikeresen letöltve"
LangString webview2Downloading ${LANG_HUNGARIAN} "A WebView2 indítótelepítőjének letöltése..."
LangString webview2InstallError ${LANG_HUNGARIAN} "Hiba: a WebView2 telepítése sikertelen. Kilépési kód: $1"
LangString webview2InstallSuccess ${LANG_HUNGARIAN} "A WebView2 sikeresen telepítve"
LangString deleteAppData ${LANG_HUNGARIAN} "Az alkalmazás adatainak törlése"
