'use strict';
// YAML is the authoring format. Only generated JSON and the English bootstrap
// enter the renderer: no YAML parser, network service or source scanner at runtime.
const fs = require('node:fs');
const path = require('node:path');
const yaml = require('js-yaml');
const root = path.resolve(__dirname, '..');
const source = path.join(root, 'locales');
const output = path.join(root, 'src', 'locales');
const read = file => yaml.load(fs.readFileSync(file, 'utf8'));
const registry = read(path.join(source, 'registry.yaml'));
function flatten(object, prefix = '', result = {}) {
  for (const [key, value] of Object.entries(object || {})) {
    const full = prefix ? `${prefix}.${key}` : key;
    if (typeof value === 'string') result[full] = value;
    else if (value && typeof value === 'object' && !Array.isArray(value)) flatten(value, full, result);
    else throw new Error(`Translation ${full} must be a string or a group.`);
  }
  return result;
}
function loadLocale(id) {
  const directory = path.join(source, id);
  if (!fs.existsSync(directory)) return {};
  return Object.fromEntries(fs.readdirSync(directory).filter(file => file.endsWith('.yaml')).sort()
    .map(file => [path.basename(file, '.yaml'), read(path.join(directory, file))]));
}
function variables(text) { return [...text.matchAll(/{{-?\s*([^},\s]+)(?:[^}]*)}}/g)].map(match => match[1]).sort(); }
function build({ check = false, strict = false } = {}) {
  const english = loadLocale(registry.default);
  const errors = [], coverage = {};
  fs.mkdirSync(output, { recursive: true });
  for (const language of registry.languages) {
    const resources = loadLocale(language.id);
    let missing = 0, total = 0;
    for(const namespace of Object.keys(resources)) if(!Object.hasOwn(english,namespace)) errors.push(language.id+'/'+namespace+' is an obsolete namespace');
    for (const [namespace, messages] of Object.entries(english)) {
      const expected = flatten(messages), actual = flatten(resources[namespace]);
      for (const [key, value] of Object.entries(expected)) {
        total++;
        if (!Object.hasOwn(actual, key)) { missing++; if (strict) errors.push(`${language.id}/${namespace}:${key} is missing`); }
        else if (!actual[key].trim()) errors.push(`${language.id}/${namespace}:${key} is empty`);
        else if (JSON.stringify(variables(value)) !== JSON.stringify(variables(actual[key]))) errors.push(`${language.id}/${namespace}:${key} interpolation differs`);
      }
      for (const key of Object.keys(actual)) if (!Object.hasOwn(expected, key)) {
        const base = key.replace(/_(?:zero|one|two|few|many|other)$/, '');
        const plural = expected[base + '_other'];
        if (base === key || !plural) errors.push(`${language.id}/${namespace}:${key} is obsolete`);
        else if (JSON.stringify(variables(plural)) !== JSON.stringify(variables(actual[key]))) errors.push(`${language.id}/${namespace}:${key} interpolation differs`);
      }
    }
    coverage[language.id] = { total, translated: total - missing, missing };
    if (!check) fs.writeFileSync(path.join(output, `${language.id}.json`), JSON.stringify(resources));
  }
  if (errors.length) throw new Error(errors.join('\n'));
  if (!check) {
    fs.writeFileSync(path.join(output, 'registry.json'), JSON.stringify(registry));
    fs.writeFileSync(path.join(output, 'english.js'), `// Generated by scripts/build-locales.js; edit locales/en/*.yaml.\nglobalThis.toolkitLocaleBootstrap = ${JSON.stringify({ registry, resources: english })};\n`);
    const keys = [...new Set(Object.entries(english).flatMap(([namespace, messages]) => Object.keys(flatten(messages)).flatMap(key => [`${namespace}:${key}`, `${namespace}:${key.replace(/_(?:zero|one|two|few|many|other)$/, '')}`])))];
    fs.writeFileSync(path.join(root, 'src', 'js', 'i18n-keys.d.ts'), `// Generated from YAML sources.\nexport type TranslationKey =\n${keys.map(key => `  | ${JSON.stringify(key)}`).join('\n')};\n`);
    fs.writeFileSync(path.join(output, 'coverage.json'), JSON.stringify(coverage, null, 2) + '\n');
    const vendor = path.join(root, 'src', 'vendor', 'i18next');
    fs.mkdirSync(vendor, { recursive: true });
    for (const file of ['dist/umd/i18next.min.js', 'LICENSE']) fs.copyFileSync(path.join(root, 'node_modules', 'i18next', file), path.join(vendor, path.basename(file)));
  }
  return coverage;
}
if (require.main === module) console.log(JSON.stringify(build({ check: process.argv.includes('--check'), strict: process.argv.includes('--strict') }), null, 2));
module.exports = { build, flatten, variables, registry };
